imports:
    - { resource: services/resources.yml }
    - { resource: services/tools.yml }

parameters:
#    parameter_name: value

services:
#    get_set_method_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#        public: false
#        tags:
#            - { name: serializer.normalizer }
    app.normalizer.snake_case:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - '@serializer.mapping.class_metadata_factory'
            - null
            - '@serializer.property_accessor'

#    object_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
#        public: false
#        tags:
#            - {name: serializer.normalizer}

    cobat.export.builder:
        class: AppBundle\Export\ExportBuilder
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:Time")'

    cobat.export.excel_builder:
        class: AppBundle\Export\ExcelExport
        arguments:
            - '@phpexcel'

    cobat.week.builder:
        class: AppBundle\Week\WeekBuilder
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:Time")'
            - '@=service("doctrine").getRepository("AppBundle:Worker")'

#    cobat.worker.normalizer:
#        class: AppBundle\Normalizer\WorkerNormalizer
#        tags:
#            - { name: serializer.normalizer }
#
#    cobat.time.normalizer:
#        class: AppBundle\Normalizer\TimeNormalizer
#        tags:
#            - { name: serializer.normalizer }

#    cobat.collection.normalizer:
#        class: AppBundle\Normalizer\ArrayNormalizer
#        tags:
#            - { name: serializer.normalizer, priority: 255 }
