imports:
    - { resource: services/resources.yml }
    - { resource: services/tools.yml }

parameters:
#    parameter_name: value

services:
#    get_set_method_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#        public: false
#        tags:
#            - { name: serializer.normalizer }
    app.normalizer.snake_case:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - '@serializer.mapping.class_metadata_factory'
            - null
            - '@serializer.property_accessor'

#    object_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
#        public: false
#        tags:
#            - {name: serializer.normalizer}

    cobat.export.builder:
        class: AppBundle\Export\ExportBuilder
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:Time")'

    cobat.export.excel_builder:
        class: AppBundle\Export\ExcelExport
        arguments:
            - '@phpexcel'

    cobat.week.builder:
        class: AppBundle\Week\WeekBuilder
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:Time")'
            - '@=service("doctrine").getRepository("AppBundle:Worker")'

    cobat.authorisation.jwt_login_authenticator:
        class: AppBundle\Security\JwtLoginAuthenticator
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'

    cobat.authorisation.jwt_authenticator:
        class: AppBundle\Security\JwtAuthenticator
        arguments:
            - '@cobat.security.user_factory'
            - '@lexik_jwt_authentication.extractor.authorization_header_extractor'
    cobat.security.user_factory:
        class: AppBundle\Security\UserFactory
        arguments:
            - '@lexik_jwt_authentication.encoder.default'
    cobat.security.user_provider:
        class: AppBundle\Security\UserProvider
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:User")'
